version: 2.1

orbs:
  php: circleci/php@1.1.0

jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - php/install-composer
      - php/install-packages

      - run: composer analyse
      - run: composer test
